APP_CBSs/urls.py
from django.urls import path
from APP_CBSs import views

app_name = 'APP_CBSs'

urlpatterns = [

    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),

]

CBVs/urls.py
from django.contrib import admin
from django.urls import path, include
from APP_CBSs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('basic_app/', include('APP_CBSs.urls', namespace='APP_CBSs'))
]

APP_CBSs/models.py
from django.db import models
from django.urls import reverse
class School(models.Model):
    name= models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('APP_CBSs:detail', kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

APP_CBSs/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy


class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'APP_CBSs/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("APP_CBSs:list")

APP_CBSs/templates/APP_CBSs/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="">School</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href={% url 'APP_CBSs:list' %}>Schools</a>
                <a class="nav-link active" href={% url 'admin:index' %}>Admin</a>
{#                <a class="nav-link active" href={% url 'APP_learning_users:register' %}>Register</a>#}
{##}
{#                {% if user.is_authenticated %}#}
{#                <a class="nav-link active" href={% url 'APP_learning_users:logout' %}>Logout</a>#}
{#                {% else %}#}
{#                <a class="nav-link active" href={% url 'APP_learning_users:user_login' %}>Login</a>#}
{#                {% endif %}#}

            </div>
        </div>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
</html>

APP_CBSs/templates/APP_CBSs/school_confirm_delete.html
{% extends 'APP_CBSs/basic_app_base.html' %}

{% block body_block %}

    <h1>Delete {{ school.name }}?</h1>

    <form method="POST">
    {% csrf_token %}

        <input type="submit" class="btn btn-danger" value="Delete">
        <a href={% url 'APP_CBSs:detail' pk=school.pk %}>Cancel</a>

    </form>

{% endblock %}

APP_CBSs/templates/APP_CBSs/school_detail.html
{% extends 'APP_CBSs/basic_app_base.html' %}

{% block body_block %}

    <div class="jumbotron">
        <h1>Welcome to the school detail page</h1>
        <h2>School details:</h2>
        <p>Name: {{ school_detail.name }}</p>
        <p>Name: {{ school_detail.principal }}</p>
        <p>Name: {{ school_detail.location }}</p>

        <h3>Students:</h3>

        {% for student in school_detail.students.all %}

        <p>{{ student.name }} who is {{ student.age }} years old.</p>

        {% endfor %}


    </div>

    <div class="container">
    <p><a class="btn btn-warning" href={% url 'APP_CBSs:update' pk=school_detail.pk %}>Update</a></p>
    </div>


{% endblock %}

APP_CBSs/templates/APP_CBSs/school_form.html
{% extends 'APP_CBSs/basic_app_base.html' %}

{% block body_block %}

    <h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
    </h1>

    <form method="POST">

    {% csrf_token %}
    {{ form.as_p }}

        <input type="submit" class="btn btn-primary" value="Submit">

    </form>

{% endblock %}

APP_CBSs/templates/APP_CBSs/school_list.html
{% extends "APP_CBSs/basic_app_base.html" %}

{% block body_block %}

    <h1>Welcome to a list of all schools</h1>

    <ol>
    {% for school in schools %}
    <h2><li><a href={{ school.id }}>{{ school.name }}</a></li></h2>
    {% endfor %}
    </ol>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href={% url 'APP_CBSs:list' %}>School</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href={% url 'APP_CBSs:list' %}>Schools</a>
                <a class="nav-link active" href={% url 'admin:index' %}>Admin</a>
{#                <a class="nav-link active" href={% url 'APP_learning_users:register' %}>Register</a>#}
{##}
{#                {% if user.is_authenticated %}#}
{#                <a class="nav-link active" href={% url 'APP_learning_users:logout' %}>Logout</a>#}
{#                {% else %}#}
{#                <a class="nav-link active" href={% url 'APP_learning_users:user_login' %}>Login</a>#}
{#                {% endif %}#}

            </div>
        </div>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block body_block %}

        <div class="jumbotron">
        <h1>Home page</h1>
        </div>
{% endblock %}